revoke delete on table "public"."table2" from "anon";

revoke insert on table "public"."table2" from "anon";

revoke references on table "public"."table2" from "anon";

revoke select on table "public"."table2" from "anon";

revoke trigger on table "public"."table2" from "anon";

revoke truncate on table "public"."table2" from "anon";

revoke update on table "public"."table2" from "anon";

revoke delete on table "public"."table2" from "authenticated";

revoke insert on table "public"."table2" from "authenticated";

revoke references on table "public"."table2" from "authenticated";

revoke select on table "public"."table2" from "authenticated";

revoke trigger on table "public"."table2" from "authenticated";

revoke truncate on table "public"."table2" from "authenticated";

revoke update on table "public"."table2" from "authenticated";

revoke delete on table "public"."table2" from "service_role";

revoke insert on table "public"."table2" from "service_role";

revoke references on table "public"."table2" from "service_role";

revoke select on table "public"."table2" from "service_role";

revoke trigger on table "public"."table2" from "service_role";

revoke truncate on table "public"."table2" from "service_role";

revoke update on table "public"."table2" from "service_role";


  create table "public"."t3" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."t3" enable row level security;

CREATE UNIQUE INDEX t3_pkey ON public.t3 USING btree (id);

alter table "public"."t3" add constraint "t3_pkey" PRIMARY KEY using index "t3_pkey";


