drop extension if exists "pg_net";

revoke delete on table "public"."my_table" from "anon";

revoke insert on table "public"."my_table" from "anon";

revoke references on table "public"."my_table" from "anon";

revoke select on table "public"."my_table" from "anon";

revoke trigger on table "public"."my_table" from "anon";

revoke truncate on table "public"."my_table" from "anon";

revoke update on table "public"."my_table" from "anon";

revoke delete on table "public"."my_table" from "authenticated";

revoke insert on table "public"."my_table" from "authenticated";

revoke references on table "public"."my_table" from "authenticated";

revoke select on table "public"."my_table" from "authenticated";

revoke trigger on table "public"."my_table" from "authenticated";

revoke truncate on table "public"."my_table" from "authenticated";

revoke update on table "public"."my_table" from "authenticated";

revoke delete on table "public"."my_table" from "service_role";

revoke insert on table "public"."my_table" from "service_role";

revoke references on table "public"."my_table" from "service_role";

revoke select on table "public"."my_table" from "service_role";

revoke trigger on table "public"."my_table" from "service_role";

revoke truncate on table "public"."my_table" from "service_role";

revoke update on table "public"."my_table" from "service_role";


  create table "public"."table2" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."table2" enable row level security;

CREATE UNIQUE INDEX table2_pkey ON public.table2 USING btree (id);

alter table "public"."table2" add constraint "table2_pkey" PRIMARY KEY using index "table2_pkey";


