revoke delete on table "public"."t3" from "anon";

revoke insert on table "public"."t3" from "anon";

revoke references on table "public"."t3" from "anon";

revoke select on table "public"."t3" from "anon";

revoke trigger on table "public"."t3" from "anon";

revoke truncate on table "public"."t3" from "anon";

revoke update on table "public"."t3" from "anon";

revoke delete on table "public"."t3" from "authenticated";

revoke insert on table "public"."t3" from "authenticated";

revoke references on table "public"."t3" from "authenticated";

revoke select on table "public"."t3" from "authenticated";

revoke trigger on table "public"."t3" from "authenticated";

revoke truncate on table "public"."t3" from "authenticated";

revoke update on table "public"."t3" from "authenticated";

revoke delete on table "public"."t3" from "service_role";

revoke insert on table "public"."t3" from "service_role";

revoke references on table "public"."t3" from "service_role";

revoke select on table "public"."t3" from "service_role";

revoke trigger on table "public"."t3" from "service_role";

revoke truncate on table "public"."t3" from "service_role";

revoke update on table "public"."t3" from "service_role";


  create table "public"."t44" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."t44" enable row level security;

CREATE UNIQUE INDEX t44_pkey ON public.t44 USING btree (id);

alter table "public"."t44" add constraint "t44_pkey" PRIMARY KEY using index "t44_pkey";


